# Add application configuration variables here, as shown below.
#
# PUSHER_APP_ID: "2954"
# PUSHER_KEY: 7381a978f7dd7f9a1117
# PUSHER_SECRET: abdc3b896a0ffb85d373
# STRIPE_API_KEY: EdAvEPVEC3LuaTg5Q3z6WbDVqZlcBQ8Z
# STRIPE_PUBLIC_KEY: pk_BRgD57O8fHja9HxduJUszhef6jCyS

test:
  TWILIO_SID: ACefbbba46f218ce1b1e92edcd0f87518f
  TWILIO_TOKEN: 5f75e74bc4fb248cd244768db58ef92a
  TWILIO_PHONE_NUMBER: 9172424025
  MAILCHIMP_API_KEY: 793c9717a80a73d21197ba9612167ce2-us7
  STRIPE_PUBLIC_KEY: pk_test_WHUKR5V6wB7I8VdYOOJIBB6v
  STRIPE_SECRET_KEY: sk_test_5VfCOBineyRvm6l07ZAUanJM
development:
  TWILIO_SID: ACefbbba46f218ce1b1e92edcd0f87518f
  TWILIO_TOKEN: 5f75e74bc4fb248cd244768db58ef92a
  TWILIO_PHONE_NUMBER: 9172424025
  MAILCHIMP_API_KEY: 793c9717a80a73d21197ba9612167ce2-us7
  STRIPE_PUBLIC_KEY: pk_test_WHUKR5V6wB7I8VdYOOJIBB6v
  STRIPE_SECRET_KEY: sk_test_5VfCOBineyRvm6l07ZAUanJM
staging:
  TWILIO_SID: ACefbbba46f218ce1b1e92edcd0f87518f
  TWILIO_TOKEN: 5f75e74bc4fb248cd244768db58ef92a
  TWILIO_PHONE_NUMBER: 9172424025
  MAILCHIMP_API_KEY: 793c9717a80a73d21197ba9612167ce2-us7
  STRIPE_PUBLIC_KEY: pk_test_WHUKR5V6wB7I8VdYOOJIBB6v
  STRIPE_SECRET_KEY: sk_test_5VfCOBineyRvm6l07ZAUanJM
production:
  TWILIO_SID: ACefbbba46f218ce1b1e92edcd0f87518f
  TWILIO_TOKEN: 5f75e74bc4fb248cd244768db58ef92a
  TWILIO_PHONE_NUMBER: 9177912149
  MAILCHIMP_API_KEY: 793c9717a80a73d21197ba9612167ce2-us7
  STRIPE_PUBLIC_KEY: pk_live_vMTyMR6p42Qtwix7r1W8OUny
  STRIPE_SECRET_KEY: sk_live_Z7yfpHo0N0chGll4IwWBQ9S7
  AIRBRAKE_API_KEY: a8i2r4b1r1a0k1e5k11L1A1B5b00m112